{% set version = "2.1.0" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-{{ version }}.tar.gz
  sha256: 80beaf63ddfbc64a0452b841d8036ca0611e049650e20afcb882f5d3c266d65f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - markupsafe

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python module that implements the jinja2.Markup string
  description: |
    MarkupSafe is a library for Python that implements a unicode string that
    is aware of HTML escaping rules and can be used to implement automatic
    string escaping. It is used by Jinja 2, the Mako templating engine, the
    Pylons web framework and many more.
  doc_url: https://pypi.python.org/pypi/MarkupSafe
  doc_source_url: https://github.com/pallets/markupsafe/blob/master/README.rst
  dev_url: https://github.com/pallets/markupsafe

extra:
  recipe-maintainers:
    - pelson
    - scopatz
    - ocefpaf
