travis:
  secure:
    BINSTAR_TOKEN: njzj4XKgR+jlzdSO6/SMVX52/OiNrEyqaCfiKG2EenphCw2yxQx1Psng8BaHs2hPBfORdBnsdacXG/8It79ugDcLTszjhFhrbyLhTs6qi1rlbeoozT+I9pICt41zdXrGC1rwweaxuo7PUGNf3xJGIZyfDAmcxHfmEnrwx1b6gfLvOI6+EmEtJZ/js09cNnWsc15BtfVdBXTe+sMCN0zo3WaXNjTSbo1AJ24j+NNbKtc+TyINHHnyg5lB5oM6kUleWMcDZFsW4QKKTaIlZpHHcoLZ5K1bgIjNkc4IUOXFVq9YFRUP3VGEZxZGf4brjIEB329it/sEv966U8e3Dp/E6fsQF2eh4a5+3MKS/WAQRZFgKg6eQxp2iL/MOPXjX0ZCHyOaep5zxzH/mQQ1bjZVXK30Kb3Jj0+/df0ZEUaVls+SUbaTmwWk2p3gzhiANmwuLh10/dh+OF/hmKM4x8p8Xdy/Q8pjrw38NE/4x9ArbXxxM5Mbb5Cts8ogkp03HYaOB0b0DNOww0oVzMwZQxt7hyoCw2rSJJL7MF0bWuDtG5BEelU36gxGzK7MHta65g/WyimBGKxlJOJE2yOGVXMV1CZ+oRowy/iAVjryUd4IjJQB/q9JWob2uX28HE1ENHgQX5lx7I6MHRZTmmY/lcQYsBHq8cbtLplMA1FTdO1s52M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
