travis:
  secure:
    BINSTAR_TOKEN: BSfIYZCQwMbB9C/aY8CWV9kN+aRrXey/olIkc6JGEL9rgPVV8ZHGtW9xL6jhmJtWmo6gfTmwApR/W1v7CONnskxxy2egmANugRyrCqe7fEZyFGqbbnxV1btG/iu7+MfmnoLmNeyh2pnPFa7JOt+OLiy4klrZd6i+IuiOAb94Ry8lH/BNEYOqlbohuOBPSy+U+Dv6um9pnqDscyrT03ahrN+DPI2QFlGhbHVN3XJzYEqTY/ers0DAHPDbivoR2mN+4ifth3IUHZXkrbRggb345tmpp2qVrONA5L7V52G+xDnWVhyhtjbB3iLuT/Qk2RhyXhAFGnmeu75ysZ3jpJT8AQYgXaF9Kw/W4s4jTQUwcIVF/ZKJMSa2GSinrv7UwDmpPTeAo/ZH/9eZOAOYYRv98IiOLftuUa5rxBZ3xwEZFYCgYTeWIFpsfU+ggGNZfKxJOTQyxOI2s01FaBMbllJDP/YwqnsvQPlwEVRQZCxxZSlDH8BgXgmhjOkyQDooJ6A+8hwJE1poCdy2AsN8IV/35QUGAML/RbrWaCVLMQmnvIEfioP83pw1o61h/Ui+/ViQPdjus7VNKr78op5k2Oijux7C7bl0YKBIEaDA0HFTjhujbT83WzyY8N4KnsgK6WtlAhzSpJoO3LUs/L2PCY/Z2lriXmfQf/Lj1dgNiSURRnw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
